---
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'Alpine'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'RedHat'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'FreeBSD'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'Debian'
- import_tasks: commonlinux.yml
  when: ansible_facts['os_family'] == 'FreeBSD'
- import_tasks: openwrt.yml
  when: ansible_facts['os_family'] == 'OpenWrt'

